---
title: "Data607_Assignment1"
author: "Ryan Weber"
date: "February 6, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set up workspace
```{r setup-workspace, echo=FALSE}
rm(list=ls())

library(dplyr)
library(stringr)

setwd("/Users/ryanweber/Desktop/CUNY/Data 607 Db/Assignments/Week 1/Assignment1/Data607_Assignment1")
```

## Read in files

### Read in data dictionary

```{r read-dictionary}
  dictionary <- read.table("data-dictionary.txt",row.names=NULL,stringsAsFactors = FALSE, sep=":")
```

### Read in data set

```{r read-dataset}
  dataset <- read.table("dataSet.txt",row.names=NULL,stringsAsFactors = FALSE, sep=",")
```

## Attempt to parse data dictionary

```{r}
colnames(dictionary) <- c("field", "values")
dictionary$field <- gsub("[0-9]+\\. ", "", dictionary$field)
dictionary$field <- gsub(" ", "", dictionary$field)
dictionary$values <- gsub(" ", "", dictionary$values)
dictionary
```

## Apply column names from dictionary to dataset
```{r}
colnames(dataset) <- gsub("-", "_", c("edibility", dictionary$field))
```

### Set poisonous as a factor
```{r}
  dataset$edibility <- factor(dataset$edibility, levels=c("e", "p"), labels=c("edible", "poisonous"))
  
```

### Parsing the rest of the columns using the data dictionary

I couldn't see how to use the values column to create a factor.  Is there an "apply" way to do this?

```{r}
  for (i in 2:length(dataset)){
    
      # set up name value pairs for the factor
      temp <- data.frame(val = unlist(strsplit(dictionary$values[i - 1], ",")), stringsAsFactors = FALSE)
      temp2 <- as.data.frame(str_split_fixed(temp$val, "=", 2), stringsAsFactors = FALSE)
      colnames(temp2) <- c("label", "level")
    
      dataset[, i] <- factor(dataset[, i], levels=temp2$level, labels=temp2$label)
 
  }
      
  head(dataset)

```

### Select off the first 4 columns

```{r}
  dataset <- dataset[, 1:4]

  head(dataset)

```

